create database ideal_cafe;
use ideal_cafe;

create table restaurants(
id tinyint auto_increment primary key,
name varchar(10) not null,
country varchar(10) not null,
adress varchar(50) unique not null,
phone varchar(17) unique not null,
e_mail varchar(50) unique not null
);
insert into restaurants (name,country,adress,phone,e_mail) values ('Ideal Cafe','USA','2147 Pick Street','+1  970-554-8037','ideal_cafe0@gmail.com'),
																  ('Ideal Cafe','USA','3535 Lake Forest Drive','+1  914-241-9241','ideal_cafe1@gmail.com'),
																  ('Ideal Cafe','USA','4288 Diamond Street','+1  828-883-6588','ideal_cafe2@gmail.com'),
																  ('Ideal Cafe','USA','108 Pride Avenue','+1  718-293-6373','ideal_cafe3@gmail.com'),
																  ('Ideal Cafe','USA','4373 Monroe Avenue','+1  941-761-4445','ideal_cafe4@gmail.com'),
																  ('Ideal Cafe','USA','3611 Red Bud Lane','+1  860-953-7410','ideal_cafe5@gmail.com'),
																  ('Ideal Cafe','USA','2700 Findley Avenue','+1  701-839-8488','ideal_cafe6@gmail.com');

create table menu(
id tinyint auto_increment primary key,
name varchar(20) unique not null
);
insert into menu (name) values ('Main Menu'),
							   ('Drinks Menu'),
							   ('Breakfast Menu'),
							   ('Desserts Menu');

		
create table menu_category(
id tinyint auto_increment primary key,
name varchar(25) unique not null,
menu_id tinyint not null,
constraint menu_category foreign key(menu_id) references menu(id)
);
insert into menu_category (name,menu_id) values ('Appetizers',1),
										('Salads',1),
										('Soups',1),
										('Paste',1),
										('Pizza',1),
										('Sandwiches And Burgers',1),
										('Sauces',1),
										('Tea',1),
										('Cofee',2),
										('Coffee Drinks',2),
										('Cold Drinks',2),
										('Lemonade',2),
										('Fresh Juices',2),
										('Milk Shake',2),
										('Non Alcoholic Cocktails',2),
										('Alcoholic Cocktails',2),
										('Signature Cocktails',2),
										('Sangria',2),
										('Vermouth',2),
										('Vodka',2),
										('Rum',2),
										('Tequila',2),
										('Gin',2),
										('Liquors',2),
										('Cognac',2),
										('Beer',2),
										('Energy Drinks',2),
										('Anisette',2),
										('Bourbon',2),
										('Breakfast',3),
										('Desserts',4);
                                        
create table category_foods(
id tinyint auto_increment primary key,
name varchar(100) not null,
about varchar(255) default null,
price tinyint not null,
weight varchar (6) not null,
menu_category_id tinyint not null,
constraint menu_category_id foreign key(menu_category_id) references menu_category(id)
);

insert into category_foods (name,about,price,weight,menu_category_id) values
('Tuna Snack','Canned tuna, poached egg, boiled potato, tartar sauce, mixed greens, sumakh, garlic dressing',7.90,'350 gr',1),
('Deep-fried dumplings',null,6.90,'150 gr',1),
('Chicken Tenders',null,8.00,'215 gr',1),
('Chicken Charlottes','Breaded minced chicken and gouda cheese, homemade potato, cheese sauce',9.90,'320 gr',1),
('Chicken and Mushrooms Profiteroles',null,6.90,'150 gr',1),
('Deep-fried dumplings','Profiteroles, gouda cheese, onion, mushrooms, chicken fillet, cream, garlic potato',9.90,'300 gr',1),
('Asian Bowl','Breaded chicken, white and red cabbage, carrot, tomato, radish, mexico mix, canned red beans, fried eggs, Asia sauce',9.90,'260 gr',1),
('Chicken "Volcano" dumplings','Potato pancakes, chicken mousse, oyster sauce, garlic, tomatoes, sesame seeds, mixed greens',6.90,'200 gr',1),
('Oriental eggplants','Eggplants, walnuts, sour cream, garlic, curry paste, coriander',6.90,'110 gr',1),
('Hummus with Foccaccia',null,6.90,'380 gr',1),
('Mashed Crunchy Potato with Spinach',null,6.90,'150 gr',1),
('Warm Potato Snack','Baby potato, omelet, sun-dried tomatoes, pickled cucumbers, fried mushrooms, red onion, green peas, dill, garlic dressing',8.50,'340 gr',1),
('Vegetarian Snack','Crunchy breaded potato patty, onion, poached egg, baked red paprika, cream cheese, green peas, "paprika" dressing',6.90,'320 gr',1),
('Tuna salad','Canned tuna, cucumber, tomato, red onion, eggs, capers, pickled cucumbers, lettuce, iceberg, lollo rosso, olive oil',10.90,'320 gr',2),
('Nicoise Salad','Canned tuna, potato pancake, poached egg, sesame seeds, tomatoes, pickled cucumber, red onion, green beans, lollo rosso, lettuce, iceberg, arugula, olive oil, vinegar',11.50,'400 gr',2),
('Asian style Meat Salad','Beef tenderloin, oyster sauce, cucumber, carrot, colored paprika, red onion, mixed greens, mint, green onion, iceberg, sesame, hot pepper, soy sauce, lemon juice, olive oil',14.90,'280 gr',2),
('Beef Tagliata','Beef tenderloin, potato pancake, tomato, balsamic glaze, piquant sauce, mixed greens',14.90,'350 gr',2),
('Potato Salad with Chicken','Chicken fillet, baby potato, tomato, red onion, pickled cucumber, green peas, garlic, mixed greens, mayonnaise',10.20,'370 gr',2),
('Chicken Salad with Bulgur and Beetroot','Marinated baked chicken fillet, tomato, cucumber, beetroot, bulgur, chickpeas, green peas, black olives, white cheese, mixed greens, olive oil, balsamic glaze',10.50,'350 gr',2),
('"Chicken salad with baby potatoes in piquant sauce"','Baked chicken fillet, tomatoes, cucumbers, garlic croutons, baby potatoes, iceberg, piquant sauce, "paprika" dressing',11.00,'500 gr',2),
('Chicken Salad with Pear and Beetroot','Marinated baked chicken fillet, pear, brown sugar, beetroot, tomato, feta cheese, peanuts, lettuce, arugula, mixed greens, olive oil',10.90,'310 gr',2),
('Vegetable salad with chicken and feta cheese','',10.50,'310 gr',2),
('Vegetable salad with chicken and feta cheese','Chicken fillet, tomato, fried peanuts, feta cheese, iceberg, arugula, lollo rosso, mixed greens, balsamic glaze',11.00,'330 gr',2),
('Chicken salad with parmesan cheese','Breaded chicken fillet, tomatoes, lettuce, iceberg, mixed greens, parmesan cheese, toasts, cream cheese, pesto sauce',10.50,'380 gr',2),
('Caesar Salad','Chicken fillet, garlic croutons, parmesan cheese, iceberg, tomato, Caesar sauce',12.80,'310 gr',2),
('Chicken Blues','Boiled chicken fillet, tomatoes, cucumbers, gouda cheese, iceberg, mayonnaise',8.00,'320 gr',2),
('Olivier salad','"Cucumber, pickled cucumber, potato, carrot, eggs, green peas, dill, mayonnaise, grilled chicken fillet, black bread with tomato and pesto sauce, mixed greens, balsamic glaze"',10.50,'350 gr',2),
('Grilled Chicken Salad','Chicken fillet, potato, tomato, mushroom, iceberg, arugula, sour cream-garlic sauce, pesto sauce',12.00,'480 gr',2),
('Asian style Salad with Fried Cheese and Edamame','Breaded white cheese, carrot, cucumber, edamame beans, boiled rice, rice vinegar, green onion, mixed greens, soya dressing',9.90,'300 gr',2),
('Greek salad','"Cucumbers, tomatoes, bell pepper, red onion, black olives, radish, feta cheese, lettuce, iceberg, vegetable sauce, olive oil"',9.50,'380 gr',2),
('Tomato soup',null,6.80,'330 gr',3),
('Mushroom soup',null,4.80,'330 gr',3),
('Lentils soup',null,4.80,'330 gr',3),
('Chicken bouillon',null,4.00,'330 gr',3),
('Noodle soup with meatballs (seasonally)','Noodles, beef, white beans',6.00,'380 gr',3),
('Okroshka (seasonally)','Yogurt, sour cream, cucumbers, greens, veal, eggs, potatoes',5.00,'330 gr',3),
('Spaghetti Bolognese','Pasta spaghetti, Bolognese sauce (minced beef, carrot, onion, garlic, tomato sauce, spices), canned peeled tomatoes, parmesan cheese',11.00,'340 gr',4),
('Ham and Mushroom Fettuccine','"Pasta fettuccine, turkey ham, eggs, mushrooms, cream"',12.80,'400 gr',4),
('Chicken and Pesto Tagliatelle','Pasta tagliatelle, chicken fillet, pesto sauce, tomato, parmesan cheese',10.90,'350 gr',4),
('Chicken Spaghetti','Pasta spaghetti, chicken fillet, cream, garlic, oyster sauce, parmesan cheese',10.90,'330 gr',4),
('Creamy Penne with Sweetcorn','Pasta penne, onion, carrot, canned sweetcorn, garlic, cream',9.00,'320 gr',4),
('Potato Dumplings with cheese sause dressing','Potato Dumplings with cheese sause dressing',7.50,'280 gr',4),
('Diabola','"Smoked sausage, chilles, tomato sauce, mozzarella cheese"',14.00,'3900 gr',5),
('Salsiccia','Sausages, bell pepper, mushrooms, tomato sauce, mozzarella cheese',12.50,'470 gr',5),
('Four Seasons','Chicken fillet, mushrooms, tomatoes, smoked sausage, tomato sauce, mozzarella cheese',14.50,'500 gr',5),
('Chicken Ranch','Chicken fillet, ranch sauce, tomato, mozzarella sauce',13.00,'450 gr',5),
('Funghi con Pollo','Chicken fillet, mushrooms, tomato sauce, mozzarella cheese',14.50,'400 gr',5),
('Pollo al Pomodoro','Chicken fillet, tomatoes, tomato sauce, mozzarella cheese',14.00,'400 gr',5),
('Caesar Pizza','Chicken fillet, iceberg, Caesar sauce, parmesan cheese, tomato sauce, mozzarella cheese',16.50,'450 gr',5),
('Chicken Barbecue','Boiled chicken fillet, barbecue sauce, tomato sauce, mozzarella cheese',3.70,'280 gr',5),
('Cheeseburger with piquant sauce','Beef patty, bun, cucumbers, pickled cucumbers, tomatoes, lettuce, gouda cheese, piquant sauce, french fries with ketchup and mayonnaise',14.00,'450 gr',6),
('Burger with cheese sauce','Beef patty, bun, cucumbers, pickled cucumbers, tomatoes, lettuce, cheese sauce, french fries with ketchup and mayonnaise',14.00,'450 gr',6),
('Club Sandwich','Toasts, chicken fillet, turkey ham, omelet, tomatoes, cucumbers, pickled cucumbers, lettuce, gouda cheeseselect *from category_foods;, piquant sauce, french fries with ketchup and mayonnaise',12.80 ,'400 gr',6),
('Caesar Roll','Lavash, chicken fillet, tomatoes, pickled cucumbers, omelette, parmesan cheese, lettuce, Caesar sauce, french fries with ketchup and mayonnaise',14.00,'400 gr',6),
('Balsamic Glaze',null,1.50,'60 gr',7),
('Mama Sitas (oyster sauce)',null,1.50,'60 gr',7),
('Adzhika',null,1.50,'60 gr',7),
('Asian Sauce',null,1.50,'60 gr',7),
('Balsamic Dressing with Olive Oil',null,1.50,'60 gr',7),
('Barbecue Sauce',null,1.50,'60 gr',7),
('Balsamic Vinegar',null,1.50,'60 gr',7),
('Berry Sauce',null,1.50,'60 gr',7),
('Sour Cream',null,1.50,'60 gr',7),
('Pepper Sauce',null,1.50,'60 gr',7),
('Curry Sauce',null,1.50,'60 gr',7),
('Ketchup',null,1.50,'60 gr',7),
('Mayonnaise',null,1.50,'60 gr',7),
('Narsharab (Pomegranate Sauce)',null,1.50,'60 gr',7),
('Piquant Sauce',null,1.50,'60 gr',7),
('Cheese Sauce',null,1.50,'60 gr',7),
('Tomato Sauce',null,1.50,'60 gr',7),
('Pesto',null,1.50,'60 gr',7),
('Paprica Dressing',null,1.50,'60 gr',7),
('Ranch Sauce',null,1.50,'60 gr',7),
('Caesar Sauce',null,1.50,'60 gr',7),
('Soy Sauce',null,1.50,'60 gr',7),
('Garlic Dressing with Greens and Olive Oil',null,1.50,'60 gr',7),
('Sweet Chili Sauce',null,1.50,'60 gr',7),
('Chocolate Sauce Hersheys',null,1.50,'60 gr',7),
('Tartar Sauce',null,1.50,'60 gr',7),
('Olive Oil',null,1.50,'60 gr',7),
('Bolognese Sauce',null,5.50,'60 gr',7),
('Tea','Soursop/Green/Jasmine/Black',4.80,'1 cup',8),
('Espresso single',null,2.90',1 cup',9),
('Espresso double',null,4.00,'1 cup',9),
('Americano',null,4.00,'1 cup',9),
('Cappuccino',null,5.50,'1 cup',9),
('Latte',null,8.00,'1 cup',9),
('Frappe',null,6.00,'1 cup',9),
('Coffee Glasse',null,6.00,'1 cup',9),
('Hot Chocolate',null,6.00,'1 cup',9),
('Salted Caramel Latte',null,,'1 cup',10),
('Sour Berry Raf',null,,'1 cup',10),
('Citrus Raf',null,7.50,'1 cup',10),
('Coffee Mocha',null,6.00,'1 cup',10),
('Espresso Freddo',null,4.00,'1 cup',10),
('Cappuccino Freddo',null,6.00 ,'1 cup',10),
('Borjomi',null,2.80,'500 ml',11),
('Bonaqua Still / Sparkling',null,1.20,'by glass',11),
('Sirab Premium Still / Sparkling',null,2.50,'330 ml',11),
('Coca-Cola / Fanta / Sprite',null,2.00,'500 ml',11),
('"Cappy" Fruit Juice',null,3.00,'280 ml',11),
('Tonic',null,3.30,'330 ml',11),
('Red Bull','Classic / Yellow / Sugar Free',6.00,'250 ml',11),
('Ice Tea',null,3.80,'1 cup',11),
('Tarragon',null,4.00,'1 cup',12),
('Black Currant',null,4.00,'1 cup',12),
('Pear and cinnamon',null,4.00,'1 cup',12),
('Green apple',null,4.00,'1 cup',12),
('Black Currant',null,4.00,'1 cup',12),
('Pear and cinnamon',null,4.00,'1 cup',12),
('Green apple',null,4.00,'1 cup',12),
('Pina Colada with Orange',null,4.00,'1 cup',12),
('Watermelon and Strawberry',null,4.00,'1 cup',12),
('Passion Fruit',null,4.00,'1 cup',12),
('Colada Mix','Pina Colada syrup, pineapple juice, banana, red grape, sparkling water 6.00 ₼None',4.00,'1 cup',12),
('Grapefruit','Grapefruit, ginger, honey, apple syrup, sparkling water',4.00,'1 cup',12),
('Basil','Green basil, red basil, cucumber, lime, sugar syrup, sparkling water',4.00,'1 cup',12),
('Tangerine','Tangerine, lime, mint, passion fruit puree, sparkling water',4.00,'1 cup',12),
('Pina Colada','White Rum, coconut liquor, pineapple juice',15.00,'1 cup',16),
('Apple',null,6.00,'280 ml',13),
('Orange',null,6.50,'280 ml',13),
('Pineapple',null,9.00,'280 ml',13),
('Grapefruit',null,9.00,'280 ml',13),
('Milkshake','Bubble / Chocolate / Strawberry',8.00,'280 ml',14),
('Kiwi Cooler','Kiwi, tarragon syrup, apple juice, lemon',7.00,'1 cup',15),
('Pleasure','Strawberry, blackberry, lime, mint, sparkling water',7.00,'1 cup',15),
('Fresh G','Ginger, strawberry, mashed raspberry, orange juice',7.00,'1 cup',15),
('Cucamba','Orange, cucumber, lime, rosemarine, lemonade',7.00,'1 cup',15),
('Grapefreshener','Red grape, coconut syrup, blackberry juice, pineapple juice',7.00,'1 cup',15),
('Non-Alcoholic Mojito',null,9.00,'1 cup',15),
('Mojito','White rum, mint leaves, sugar syrup, soda water, lemon juice',10.00,'1 cup',16),
('Margarita','Tequila, triple sec, lemon juice',12.00,'1 cup',16),
('Bloody Mary','Vodka, tomato juice, Tabasco, salt, Worchestershire sauce, pepper, lemon juice',14.00,'1 cup',16),
('Cosmopolitan','Vodka, triple sec, cranberry juice, lemon juice',10.00,'1 cup',16),
('Long Island Iced Tea','Triple sec, white rum, gin, tequila, vodka, lemon juice, Coca-Cola',13.00,'1 cup',16),
('Pina Colada','White Rum, coconut liquor, pineapple juice',15.00,'1 cup',16),
('Daiquiri','Banana / Pineapple / Strawberry',10.00,'280 ml',16),
('Sex on the Beach','Peach liquor, vodka, orange juice, cranberry juice',10.00,'1 cup',16),
('Irish Coffee','"Jameson, Irish syrup, hot coffee, cream',12.00,'1 cup',16),
('Sweet Jackie','Bourbon, triple sec liquor, caramel, lemon, egg-white',13.50,'1 cup',17),
('Kill Me Softly','Tequila, coconut syrup, almond syrup, lemon, green chili pepper, soda water',12.00,'1 cup',17),
('Cardinals Kiss','Red grape, vodka, cinnamon, red wine',12.00,'1 cup',17),
('Magic Safari','Mashed passion fruit, Prosecco',13.00,'1 cup',17),
('Peach on the Beach','Gin, mashed passion fruit, orange & peach juice',12.00,'1 cup',17),
('Cucu JOY','Vodka, triple sec, kiwi, cucumber, elderflower syrup, lime',12.00,'1 cup',17),
('Non-Alcoholic Sangria',null,7.00,'1 cup',18),
('Red Wine Sangria',null,10.00,'1 cup',18),
('White Wine Sangria',null,10.00,'1 cup',18),
('Martini Rosso',null,7.00,'80 ml',19),
('Martini Bianco',null,7.00,'80 ml',19),
('Martini Extra Dry',null,7.00,'80 ml',19),
('Smirnoff',null,6.00,'50 ml',20),
('Finlandia',null,6.00,'50 ml',20),
('Russian Standard',null,6.00,'50 ml',20),
('Beluga',null,10.00,'50 ml',20),
('Grappa',null,15.00,'50 ml',20),
('Yeni Rakı',null,6.00,'40 ml',20),
('Bacardi Superior',null,7.00,'0.4 l',21),
('Captain Morgan',null,7.00,'0.4 l',21),
('Bacardi Black',null,7.00,'0.4 l',21),
('Sierra Silver',null,6.00,'40 ml',22),
('Sierra Gold',null,6.00,'40 ml',22),
('Olmeca Blanco',null,6.00,'40 ml',22),
('Olmeca Gold',null,6.00,'40 ml',22),
('Beefeater',null,6.00,'40 ml',23),
('Sapphire',null,6.00,'40 ml',23),
('Bailey’s',null,5.50,'40 ml',24),
('Malibu',null,6.00,'40 ml',24),
('Smirnoff',null,6.00,'40 ml',24),
('Kahlua',null,6.00,'40 ml',24),
('Cointreau',null,7.00,'40 ml',24),
('Amaretto Disaronno',null,7.00,'40 ml',24),
('Hennessy VS',null,9.00,'40 ml',24),
('Hennesy VSOP',null,15.00,'40 ml',25),
('Remy Martin VSOP',null,10.00,'40 ml',25),
('Remy Martin XO',null,30.00,'40 ml',25),
('Peach Liquer',null,7.00,'40 ml',25),
('Baltika-0%',null,4.00,'470 ml',26),
('Cider Somersby Apple',null,5.50,'400 ml',26),
('Cider Somersby Blackberry',null,5.50,'400 ml',26),
('Carlsberg',null,6.50,'470 ml',26),
('Kronenbourg-Blanc',null,8.00,'460 ml',26),
('Corona',null,5.50,'400 ml',26),
('Cider Somersby Apple',null,7.50,'400 ml',26),
('Red Bull','Classic / Yellow / Sugar Free',5.50,'400 ml',27),
('Absinth',null,9.00,'40 ml',28),
('Sambuka',null,9.00,'40 ml',28),
('Jim Beam',null,6.00,'40 ml',29),
('Oatmeal','Oat, milk, butter, succade (for choice)',4.00,null,30),
('Pizza-Omelet','Eggs, colored paprika, green onion, tomatoes, feta cheese',6.00,null,30),
('Spinach Omelet','Eggs, chicken fillet, spinach, onion, served with sour cream',7.50,null,30),
('Kruassan',null,4.00,null,31),
('Tiramisu',null,8.80,null,31);

select *from category_foods;
select *from menu;
select *from menu_category;
select *from restaurants;















